# Arquivo de configuração para Streamlit Cloud
# Copie este arquivo para .streamlit/secrets.toml no Streamlit Cloud

# API Key do Groq
chave = "sua-api-key-do-groq-aqui"

# Outras configurações
[general]
debug = false
log_level = "info"

[server]
max_upload_size = 200
